ProgettoCinema/TheSpaceCinema.Web/Models/CinemaView.cs
using System.ComponentModel.DataAnnotations;
using TheSpaceCinema.Model;

namespace TheSpaceCinema.Web.Models
{
    public class CinemaView
    {
        private int idCinema;
        private string nomeCinema;

        [Display(Name = "Codice Cinema")]
        public int IdCinema
        {
            get { return idCinema; }
            set { idCinema = value; }
        }

        [Display(Name = "Nome del Cinema")]
        public string NomeCinema
        {
            get { return nomeCinema; }
            set { nomeCinema = value; }
        }

        public CinemaView(Cinema cinema)
        {
            IdCinema = cinema.IdCinema;
            NomeCinema = cinema.NomeCinema;
        }
    }
}

ProgettoCinema/TheSpaceCinema.Web/Models/FilmView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TheSpaceCinema.Model;

namespace TheSpaceCinema.Web.Models
{
    public class FilmView
    {
        private int idFilm;
        private string titoloFilm;
        private string autore;
        private string produttore;
        private string genere;
        private int durata;

        [Display(Name = "Codice del Film")]
        public int IdFilm
        {
            get { return idFilm; }
            set { idFilm = value; }
        }

        [Display(Name = "Titolo del Film")]
        public string TitoloFilm
        {
            get { return titoloFilm; }
            set { titoloFilm = value; }
        }

        [Display(Name = "Regista")]
        public string Autore
        {
            get { return autore; }
            set { autore = value; }
        }

        public string Produttore
        {
            get { return produttore; }
            set { produttore = value; }
        }

        public string Genere
        {
            get { return genere; }
            set { genere = value; }
        }

        public int Durata
        {
            get { return durata; }
            set { durata = value; }
        }

        public FilmView(Film film)
        {
            IdFilm = film.IdFilm;
            TitoloFilm = film.TitoloFilm;
            Autore = film.Autore;
            Produttore = film.Produttore;
            Genere = film.Genere;
            Durata = film.Durata;
        }
    }
}

ProgettoCinema/TheSpaceCinema.Web/Models/SalaCinematograficaView.cs
using System.ComponentModel.DataAnnotations;
using TheSpaceCinema.Model;

namespace TheSpaceCinema.Web.Models
{
    public class SalaCinematograficaView
    {
        private int idSalaCinematografica;
        private string nomeSalaCinematografica;
        private int capienza;

        [Display(Name = "Codice di Sala")]
        public int IdSalaCinematografica
        {
            get { return idSalaCinematografica; }
            set { idSalaCinematografica = value; }
        }

        [Display(Name = "Numero di Sala")]
        public string NomeSalaCinematografica
        {
            get { return nomeSalaCinematografica; }
            set { nomeSalaCinematografica = value; }
        }

        [Display(Name = "Capienza Massima")]
        public int Capienza
        {
            get { return capienza; }
            set { capienza = value; }
        }

        public SalaCinematograficaView(SalaCinematografica salaCinematografica)
        {
            IdSalaCinematografica = salaCinematografica.IdSalaCinematografica;
            NomeSalaCinematografica = salaCinematografica.NomeSalaCinematografica;
            Capienza = salaCinematografica.Capienza;
        }
    }
}

ProgettoCinema/TheSpaceCinema.Web/Models/SpettatoreView.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using TheSpaceCinema.Model;

namespace TheSpaceCinema.Web.Models
{
    public class SpettatoreView
    {
        private int idSpettatore;
        private string nomeSpettatore;
        private string cognomeSpettatore;
        private DateTime dataNascita;

        [Display(Name = "Pass Spettatore")]
        public int IdSpettatore
        {
            get { return idSpettatore; }
            set { idSpettatore = value; }
        }

        [Display(Name = "Nome")]
        public string NomeSpettatore
        {
            get { return nomeSpettatore; }
            set { nomeSpettatore = value; }
        }

        [Display(Name = "Cognome")]
        public string CognomeSpettatore
        {
            get { return cognomeSpettatore; }
            set { cognomeSpettatore = value; }
        }

        [Display(Name = "Età")]
        public DateTime DataNascita
        {
            get { return dataNascita; }
            set { dataNascita = value; }
        }

        public SpettatoreView(Spettatore spettatore)
        {
            IdSpettatore = spettatore.IdSpettatore;
            NomeSpettatore = spettatore.NomeSpettatore;
            CognomeSpettatore = spettatore.CognomeSpettatore;
            DataNascita = spettatore.DataNascita;
        }
    }
}

ProgettoCinema/TheSpaceCinema.Web/Controllers/CinemaController.cs
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using TheSpaceCinema.SqlProvider;
using TheSpaceCinema.Web.Models;

namespace TheSpaceCinema.Web.Controllers
{
    public class CinemaController : Controller
    {
        private CinemaSqlProvider _cinemaSqlProvider;

        public CinemaController()
        {
            _cinemaSqlProvider = new CinemaSqlProvider(ConfigurationManager.ConnectionStrings["_connectionString"].ConnectionString);
        }

        public ActionResult Index()
        {
            var cinemaList = _cinemaSqlProvider.GetAll().Select(c => new CinemaView(c));
            return View(cinemaList);
        }
    }
}

ProgettoCinema/TheSpaceCinema.Web/Controllers/SalaCinematograficaController.cs
using System.Configuration;
using System.Linq;
using System.Web.Mvc;
using TheSpaceCinema.SqlProvider;
using TheSpaceCinema.Web.Models;

namespace TheSpaceCinema.Web.Controllers
{
    public class SalaCinematograficaController : Controller
    {
        private SalaCinematograficaSqlProvider _salaCinematograficaSqlProvider;

        public SalaCinematograficaController()
        {
            _salaCinematograficaSqlProvider = new SalaCinematograficaSqlProvider(ConfigurationManager.ConnectionStrings["_connectionString"].ConnectionString);
        }

        public ActionResult Index()
        {
            var saleProiezioneList = _salaCinematograficaSqlProvider.GetAll().Select(s => new SalaCinematograficaView(s));
            return View(saleProiezioneList);

        }
    }
}

ProgettoCinema/TheSpaceCinema.Web/Views/Cinema/Index.cshtml
@model IEnumerable<TheSpaceCinema.Web.Models.CinemaView>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdCinema)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeCinema)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdCinema)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeCinema)
        </td>
        @*<td>
            @Html.ActionLink("Sale di Proiezione", "Index", "SalaCinematografica", new {​​​​ id = item.IdCinema }​​​​, null)
        </td>*@
    </tr>
}

</table>

ProgettoCinema/TheSpaceCinema.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ProgettoCinema/TheSpaceCinema.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ProgettoCinema/TheSpaceCinema.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

ProgettoCinema/TheSpaceCinema.Web/Views/SalaCinematografica/Index.cshtml
@model IEnumerable<TheSpaceCinema.Web.Models.SalaCinematograficaView>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IdSalaCinematografica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NomeSalaCinematografica)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Capienza)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IdSalaCinematografica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NomeSalaCinematografica)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Capienza)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

ProgettoCinema/TheSpaceCinema.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cinema", "Index", "Cinema")</li>
                    <li>@Html.ActionLink("Sale di Proiezione", "Index", "SalaCinematografica")</li>
                    <li>@Html.ActionLink("Film", "Index", "Film")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>